#!/bin/zsh

print_line_sep(){
  LineWidth=${1:-80}
  SepChar=${2:-'\x2d'}

  for i in $(seq $LineWidth)
  do
    # echo -n "-"
    echo -n $SepChar
  done
  echo ''
}


watch(){
  binary=$1
  shift

  while true
  do
    inotifywait -q -e modify $@
    print_line_sep 80 '='
    echo -n "[$(date +"%Y/%m/%d %H:%M:%S")] Updated"
    print_line_sep 80 '='
    if (stack build) then
      echo ""
      stack exec $binary
    else
      echo " (skip execution)"
    fi
  done
}
