#!/bin/sh

DEBUG=false
OPTIONS=""

if [ "x$1" = "xdebug" ]
then
  DEBUG=true
fi

source ./watcher.sh

execute_stack(){
  FLAG=""

  if [ "$DEBUG" = "true" ]
  then
    FLAG="--flag hs-othello:FastCompile"
    OPTIONS="cpu"
  fi

  BuildCommand="stack build $FLAG"
  ExecCommand="stack exec hothello $OPTIONS"

  if $BuildCommand
  then
    echo "(Build Finished - Execute: $ExecCommand)"
    ExecCommand="stack 
  else
    echo "(... Skipped Execution ...)"
  fi
}

watch execute_stack $(find -iname \*.hs) hs-othello.cabal stack.yaml README.md
