#!/bin/zsh
while true
do
  inotifywait -q -e modify **/*.hs hs-othello.cabal stack.yaml README.md
  Time="$(date +"%Y/%m/%d %H:%M:%S")"
  if (stack build) then
    echo "[$Time] Updated"
    echo "[$Time] Updated"
    stack exec hothello
  else
    echo "[$Time] Updated (skip execution)"
  fi
done

