#!/bin/zsh
#
while true
do
  inotifywait -q -e modify **/*.hs hs-othello.cabal stack.yaml README.md

  for i in $(seq 80)
  do
    echo -n "-"
  done

  echo -n "[$(date +"%Y/%m/%d %H:%M:%S")] Updated"
  if (stack build) then
    echo ""
    stack exec hothello
  else
    echo " (skip execution)"
  fi

done

